export const GM_COMMAND_TUTORIAL = [
  '## tavern_commands 统一规范（教程）',
  '',
  '仅输出一个 JSON 代码块，包含字段：text(字符串)、mid_term_memory(字符串)、tavern_commands(对象)。所有变更必须有 text 中的明确依据。',
  '格式要求:',
  '- text: 必须是字符串类型，不能为null或undefined',
  '- mid_term_memory: 必须是字符串类型(非空时)，不能是数组或对象',
  '- tavern_commands: 必须是对象类型，包含set/add/push/pull/delete字段，不能是数组',
  '',
  '### tavern_commands（对象形式，推荐）',
  "tavern_commands = { set:{'character.saveData.路径':值}, add:{'character.saveData.路径':数值}, push:[{key:'character.saveData.路径',value:值}], pull:[{key:'character.saveData.路径',value:值}], delete:['character.saveData.路径'] }",
  '说明：路径必须以 character.saveData. 开头，使用点号路径；省略 scope 时默认 chat；禁止整体覆盖 character.saveData；禁止写世界信息与玩家出生地。',
  '',
  '### 物品规范',
  "- 仅 set 到 'character.saveData.背包.物品.<物品ID>'（对象键），禁止 set/push 整个 '物品'。",
  '- 类型：仅允许 装备 | 功法 | 其他。',
  '- 基础：物品ID/名称/类型/品质{quality,grade}/数量/描述(与 text 对应)。',
  '- 品质：quality 用游戏枚举(如 凡/黄/玄/地/天/仙/神)；grade=0..10。',
  '',
  '### 状态效果规范',
  '- 字段：类型(buff|debuff, 小写)/状态名称/状态描述/时间(字符串)/可选强度/来源。',
  '',
  '### 位置与地图',
  '- 常规仅 set 位置.坐标(单次偏移≤100) 与 位置.描述。',
  '- 仅叙事确有其事时 push 地点(最小对象：名称/类型/描述/位置{X,Y}/重要)。',
  '',
  '### 人物关系',
  '- 仅叙事出现明确互动时 set 到 人物关系.<姓名>，包含 人物关系/好感度/人物记忆。',
  '',
  '### 示例（对象/数组混用）',
  '{"tavern_commands": {"set": {"character.saveData.玩家角色状态.位置.描述":"村口石桥边","character.saveData.玩家角色状态.位置.坐标": {"X":123,"Y":456}}, "add": {"character.saveData.玩家角色状态.修为.当前":1}, "push": [{"key":"character.saveData.玩家角色状态.状态效果","value":{"类型":"debuff","状态名称":"饥肠辘辘","状态描述":"饥饿导致虚弱。","时间":"30分钟"}}], "pull": [], "delete": [] }}',
  '',
  '### 生成纪律（最高权限）',
  '- 文本先行，指令后置：所有变更必须有 text 里的明确依据。',
  '- 不得写入世界信息/玩家出生地/整体覆盖存档。',
  '- 难度 normal/medium/hard；进入他人地图强制 hard。hard 时严格自审并修正不合理变更。'
].join('\n');

